
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:43 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:43 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/Hostx86/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      2
      Microsoft (R) C/C++ Optimizing Compiler Version 19.44.35222 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.44.35222.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:43 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/Hostx86/x64/cl.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.44.35222 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCXXCompilerId.cpp
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/Administrator/Documents/GitHub/E.V3/kernel_cpp/temp_build/CMakeFiles/3.31.6-msvc6/CompilerIdCXX/CMakeCXXCompilerId.obj
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1288 (message)"
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:43 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\Users\\Administrator\\Documents\\GitHub\\E.V3\\kernel_cpp\\temp_build\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:43 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/Administrator/Documents/GitHub/E.V3/kernel_cpp/temp_build/CMakeFiles/CMakeScratch/TryCompile-011tk5"
      binary: "C:/Users/Administrator/Documents/GitHub/E.V3/kernel_cpp/temp_build/CMakeFiles/CMakeScratch/TryCompile-011tk5"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Administrator/Documents/GitHub/E.V3/kernel_cpp/temp_build/CMakeFiles/CMakeScratch/TryCompile-011tk5'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_5815c\\fast
        	"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX86\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_5815c.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_5815c.dir\\build
        Building CXX object CMakeFiles/cmTC_5815c.dir/CMakeCXXCompilerABI.cpp.obj
        	"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_5815c.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=C:\\Users\\Administrator\\Documents\\GitHub\\E.V3\\kernel_cpp\\temp_build\\CMakeFiles\\CMakeScratch\\TryCompile-011tk5 --filter-prefix="Note: including file: " -- C:\\PROGRA~2\\MICROS~2\\2022\\BUILDT~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx86\\x64\\cl.exe @C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\nm5811.tmp
        CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_5815c.exe
        	"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe" -E vs_link_exe --msvc-ver=1944 --intdir=CMakeFiles\\cmTC_5815c.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests -- C:\\PROGRA~2\\MICROS~2\\2022\\BUILDT~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx86\\x64\\link.exe /nologo @CMakeFiles\\cmTC_5815c.dir\\objects1.rsp @C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\nm59A8.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_5815c.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_5815c.dir/embed.manifest
        RC Pass 1:
        rc /fo CMakeFiles\\cmTC_5815c.dir/manifest.res CMakeFiles\\cmTC_5815c.dir/manifest.rc
        RC Pass 1: command "rc /fo CMakeFiles\\cmTC_5815c.dir/manifest.res CMakeFiles\\cmTC_5815c.dir/manifest.rc" failed (exit code 0) with the following output:
        no such file or directoryNMAKE : fatal error U1077: '"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe" -E vs_link_exe --msvc-ver=1944 --intdir=CMakeFiles\\cmTC_5815c.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests -- C:\\PROGRA~2\\MICROS~2\\2022\\BUILDT~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx86\\x64\\link.exe /nologo @CMakeFiles\\cmTC_5815c.dir\\objects1.rsp @C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\nm59A8.tmp' : return code '0xffffffff'
        Stop.
        NMAKE : fatal error U1077: '"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX86\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_5815c.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_5815c.dir\\build' : return code '0x2'
        Stop.
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:43 (project)"
    checks:
      - "Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/Hostx86/x64/cl.exe"
    directories:
      source: "C:/Users/Administrator/Documents/GitHub/E.V3/kernel_cpp/temp_build/CMakeFiles/CMakeScratch/TryCompile-p4o8ok"
      binary: "C:/Users/Administrator/Documents/GitHub/E.V3/kernel_cpp/temp_build/CMakeFiles/CMakeScratch/TryCompile-p4o8ok"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Administrator/Documents/GitHub/E.V3/kernel_cpp/temp_build/CMakeFiles/CMakeScratch/TryCompile-p4o8ok'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_d59d9\\fast
        	"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX86\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_d59d9.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_d59d9.dir\\build
        Building CXX object CMakeFiles/cmTC_d59d9.dir/testCXXCompiler.cxx.obj
        	"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_d59d9.dir\\testCXXCompiler.cxx.obj.d --working-dir=C:\\Users\\Administrator\\Documents\\GitHub\\E.V3\\kernel_cpp\\temp_build\\CMakeFiles\\CMakeScratch\\TryCompile-p4o8ok --filter-prefix="Note: including file: " -- C:\\PROGRA~2\\MICROS~2\\2022\\BUILDT~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx86\\x64\\cl.exe @C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\nm5AA1.tmp
        testCXXCompiler.cxx
        Linking CXX executable cmTC_d59d9.exe
        	"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe" -E vs_link_exe --msvc-ver=1944 --intdir=CMakeFiles\\cmTC_d59d9.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests -- C:\\PROGRA~2\\MICROS~2\\2022\\BUILDT~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx86\\x64\\link.exe /nologo @CMakeFiles\\cmTC_d59d9.dir\\objects1.rsp @C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\nm5B00.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_d59d9.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_d59d9.dir/embed.manifest
        RC Pass 1:
        rc /fo CMakeFiles\\cmTC_d59d9.dir/manifest.res CMakeFiles\\cmTC_d59d9.dir/manifest.rc
        RC Pass 1: command "rc /fo CMakeFiles\\cmTC_d59d9.dir/manifest.res CMakeFiles\\cmTC_d59d9.dir/manifest.rc" failed (exit code 0) with the following output:
        no such file or directoryNMAKE : fatal error U1077: '"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe" -E vs_link_exe --msvc-ver=1944 --intdir=CMakeFiles\\cmTC_d59d9.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests -- C:\\PROGRA~2\\MICROS~2\\2022\\BUILDT~1\\VC\\Tools\\MSVC\\1444~1.352\\bin\\Hostx86\\x64\\link.exe /nologo @CMakeFiles\\cmTC_d59d9.dir\\objects1.rsp @C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\nm5B00.tmp' : return code '0xffffffff'
        Stop.
        NMAKE : fatal error U1077: '"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX86\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_d59d9.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_d59d9.dir\\build' : return code '0x2'
        Stop.
        
      exitCode: 2
...
